# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e78758de0d90cc98293a6b1471e21b06dacf31f97756e4ec9b5c4f61a519ee6f24ebcca9eb81cb4526a0c6bf783890b6f1ad781e818e75de129125ff464102a

test:
  secret_key_base: 95da7c76d12522c4983b816459c51b9526f5e9f5137f1c508773496f2b8021e6b3a9959d632fdd00d4f9992b6bdd4318953f3683481900e1ef800fea47427bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
